# Generated by Django 3.1.7 on 2021-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210429_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('mas_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
